name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability. 
version: 1.1.1+10
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.csdcorp.speech_to_text
    pluginClass: SpeechToTextPlugin
